import os

# Solicita as informações ao usuário
os.system("git init")
print("========================================================================")
print("|                                                                      |")
print("|              𝗔𝗱𝗶𝗰𝗶𝗼𝗻𝗲 𝘂𝗺 𝗻𝗼𝘃𝗼 𝗿𝗲𝗽𝗼́𝘀𝗶𝘁𝗼𝗿𝗶𝗼 𝗻𝗼 𝗚𝗶𝘁𝗛𝘂𝗯😺💾               |")
print("|                                                                      |")
print("|                                                                      |")
print("|                                                                      |")
print("|                       .^7J5GBB#####BGPY?!:.                          |")
print("|                    ^?5B##&############&&##GY!:                       |")
print("|                 :?G#&&#####################&&#5!.                    |")
print("|               :Y#&##&&&&################&&&&&#&&G7.                  |")
print("|              ?#&####77?5G#&&########&&&#PY?!J####&G~                 |")
print("|            .5&####&Y     ^77~^^:::^^~7!:     G####&#?                |")
print("|           .P&#####&5                        .B######&?               |")
print("|           Y&#######?                        .Y########!              |")
print("|          ~########!                           J&#####&G              |")
print("|          J&#####&P                            .B#######^             |")
print("|          5&#####&5                            .B######&!             |")
print("|          Y&######G.                           ^########~             |")
print("|          !&######&J                          .P&######B.             |")
print("|           P&####&&&Y:                       ^P&######&?              |")
print("|           ^B&##G5P#&#57^.              .:~?P#&######&5               |")
print("|            ^B&#G?::J#&&#BGP!        .JPGB#&&#######&5.               |")
print("|             :5&&&B! ^YGBBB5.         ^#&#########&#?                 |")
print("|               !G&&#?.  ..             G########&#5^                  |")
print("|                 !P#&#P5YY57           G#####&&BY^                    |")
print("|                   :7PB&&&@Y           G&&&#GY!.                      |")
print("|                      .~7Y5!           ?5J!^.                         |")
print("|                                                                      |")
print("|                                                                      |")
print("| Criado por Gustavo Nunes da Silva 🖥️                                 |")
print("========================================================================")

nome = input("| Digite seu nome😊: ")
email = input("| Digite seu email 📩: ")
os.system(f'git config user.name "{nome}"')
os.system(f'git config user.email "{email}"')
os.system("git add .")


print("| Deseja ver o git status ? 🤔")
opção = input("| Digite sua opção -> S (sim) ou N (não):")

if(opção == "S" or "s" or "sim" or "Sim"):
    status = os.system("git status")
    print(status)



mensagem = input("| Digite a mensagem do commit 📨: ")
os.system(f'git commit -m "{mensagem}"')
link = input("| Digite o link do repositório remoto 🔗: ")
os.system(f'git remote add origin {link}')
os.system("git branch -M main")
os.system("git push -u origin main")
    
print("========================================================================")
print("|                                                                      |")
print("|       \n 𝗥𝗲𝗽𝗼𝘀𝗶𝘁𝗼́𝗿𝗶𝗼 𝗰𝗼𝗻𝗳𝗶𝗴𝘂𝗿𝗮𝗱𝗼 𝗲 𝗰𝗼́𝗱𝗶𝗴𝗼 𝗲𝗻𝘃𝗶𝗮𝗱𝗼 𝗰𝗼𝗺 𝘀𝘂𝗰𝗲𝘀𝘀𝗼 ✅!       |")
print("|                                                                      |")
print("|                                                                      |")
print("|                                                                      |")
print("|                       .^7J5GBB#####BGPY?!:.                          |")
print("|                    ^?5B##&############&&##GY!:                       |")
print("|                 :?G#&&#####################&&#5!.                    |")
print("|               :Y#&##&&&&################&&&&&#&&G7.                  |")
print("|              ?#&####77?5G#&&########&&&#PY?!J####&G~                 |")
print("|            .5&####&Y     ^77~^^:::^^~7!:     G####&#?                |")
print("|           .P&#####&5                        .B######&?               |")
print("|           Y&#######?                        .Y########!              |")
print("|          ~########!                           J&#####&G              |")
print("|          J&#####&P                            .B#######^             |")
print("|          5&#####&5                            .B######&!             |")
print("|          Y&######G.                           ^########~             |")
print("|          !&######&J                          .P&######B.             |")
print("|           P&####&&&Y:                       ^P&######&?              |")
print("|           ^B&##G5P#&#57^.              .:~?P#&######&5               |")
print("|            ^B&#G?::J#&&#BGP!        .JPGB#&&#######&5.               |")
print("|             :5&&&B! ^YGBBB5.         ^#&#########&#?                 |")
print("|               !G&&#?.  ..             G########&#5^                  |")
print("|                 !P#&#P5YY57           G#####&&BY^                    |")
print("|                   :7PB&&&@Y           G&&&#GY!.                      |")
print("|                      .~7Y5!           ?5J!^.                         |")
print("|                                                                      |")
print("|                                                                      |")
print("| Criado por Gustavo Nunes da Silva 🖥️                                 |")
print("========================================================================")
